spring:
   profiles:
      active: panji
---
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    activate:
      on-profile: panji
  application:
    name: Panji
  datasource:
      url: jdbc:postgresql://localhost:5432/VCARD
      username: postgres
      password: 123456
      driverClassName: org.postgresql.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.PostgreSQLDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
server:
  max-http-header-size: 10000000
  port: 8110
  error:
    whitelabel:
      enabled: false
    path: /error
URL:
  FILE_IN: C:\\Image
  FILE_PRIEVIEW: C:\\Image
  FILE_UPLOAD: C:\\Users\\Raihan.fadhlullah\\Documents\\GitHub\\vCard\\src\\main\\resources\\IMAGE
---